# Generated by Django 5.1.5 on 2025-01-21 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos_prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
    ]
